name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you? Please use either a Royal Road Username or an Email. 
      placeholder: "ex. email@example.com"
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Please provide enough info about what happened to help us reproduce this issue. Use a step by step process. 

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: "Tell us what you see!"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the APP are you running? You can find the app version in the "About us" page within the app. 
      placeholder: "[e.g. 1.3.355]"
    validations:
      required: true
  - type: input
    id: what-device
    attributes:
      label: What device are you using?
      placeholder: "[e.g. iPhone6]"
    validations:
      required: true
  - type: input
    id: what-OS
    attributes:
      label: What OS are you using?
      placeholder: "[e.g. iOS 8.1]"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
